- name: nginx
  hosts: webservers
  become: yes
  vars_files: vars/main.yml
  tasks:
  - import_tasks: tasks/install.yml
  - import_tasks: tasks/config.yml
  handlers:
  - import_tasks: handlers/reload.yml
  - import_tasks: handlers/restart.yml
