- name: ensure apache is at the latest version
  apt:
    name: apache2
    state: latest

- name: write the apache config file
  notify: restart apache
  template:
    src: templates/ports.conf.j2
    dest: /etc/apache2/ports.conf

- name: write the apache index page
  notify: restart apache
  template:
    src: templates/index.conf.j2
    dest: /var/www/html/index.html

- name: ensure apache is running
  service:
    name: apache2
    state: started
