---
- name: Copy the job script into desired location
  copy:
    src: "files/{{ job_name }}.sh"
    dest: "/usr/local/bin"

- name: Set permissions for directories
  shell: "chmod +x /usr/local/bin/{{ job_name }}.sh"

- name: Prune dangling/unused docker containers/images weekly
  cron:
    name: " dangling containers/images pruner"
    user: "root" # For a specific user
    minute: "30" # In the 30rd minute.
    hour: "1" # In the 1rd hour.
    weekday: "fri" # at every friay
    cron_file: "{{ job_name }}" # name of the cronjob in /etc/cron.d
    job: "/usr/local/bin/{{ job_name }}.sh" # the job to be executed
